# used by vps 

version: '3.9'
services:
    client:
        image: ghcr.io/c-bv/next-portfolio:main
        restart: unless-stopped
        expose:
            - 3000
        networks:
            - nginx-proxy

networks:
    nginx-proxy:
        external: true
