version: '3.9'
services:
    client:
        build:
            context: .
            dockerfile: ./.docker/Dockerfile
        restart: unless-stopped
        expose:
            - 80
        networks:
            - nginx-proxy

networks:
    nginx-proxy:
        external: true
