name: Deploy to VPS

on:
    push:
        branches: ['main']

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}
    BRANCH: ${{ github.ref }}

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Debug
              run: |
                  echo ${{ secrets.SSH_HOST }}
                  echo ${{ secrets.USERNAME }}
                  echo ${{ github.ref }}

            # - name: Deploy to VPS
            #   uses: appleboy/ssh-action@v1.0.0
            #   with:
            #       host: ${{ secrets.SSH_HOST }}
            #       username: ${{ secrets.USERNAME }}
            #       key: ${{ secrets.KEY }}
            #       port: ${{ secrets.PORT }}
            #       script: |
            #         docker login $REGISTRY -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
            #         docker pull $REGISTRY/$IMAGE_NAME:main
            #         docker-compose -f docker-compose.yml up -d
